import {menu,total,makePlans} from './feast-plans.js';
const $=s=>document.querySelector(s), planner=$('#planner'),body=$('#planner-body'),pack=$('#packaging-dialog');
let state={people:2,veg:0,budget:null,preferred:'chicken',step:0,items:[]},disposeViewer=null,viewerTicket=0;
const money=n=>`AED ${n}`;
function show(dialog){dialog.showModal()}
function openPlan(people,preferred){state={people:people||2,veg:preferred==='veg'?(people||2):0,budget:null,preferred:preferred||'chicken',step:people?1:0,items:[]};render();show(planner)}
function back(){state.step=Math.max(0,state.step-1);render()}
function next(){state.step++;render()}
function budgetNote(amount){return state.budget&&amount>state.budget?`<p class="budget-warning">${money(amount-state.budget)} above your ${money(state.budget)} food budget. Adjust the dishes or change your budget.</p>`:''}
function render(){
 if(state.step===0){body.innerHTML=`<p class="step-meta">1 OF 3 · YOUR TABLE</p><p class="chat-bubble">How many people are joining the feast?</p><div class="choice-grid">${[1,2,3,4,6,8].map(n=>`<button data-people="${n}">${n} ${n===1?'person':'people'}</button>`).join('')}</div><label class="field-label" for="diners">Or choose a number from 1–10</label><form id="people-form"><input class="planner-input" id="diners" type="number" min="1" max="10" step="1" value="${state.people}" required><div class="planner-actions"><button class="gold-button">Continue</button></div></form><p class="planner-note">A guided menu planner. No account or personal details needed.</p>`}
 if(state.step===1){body.innerHTML=`<p class="step-meta">2 OF 3 · FOOD PREFERENCES</p><p class="chat-bubble">A table for ${state.people}. How many people would like vegetarian biryani?</p><form id="veg-form"><label class="field-label" for="vegetarians">Vegetarian diners</label><select class="planner-input" id="vegetarians">${Array.from({length:state.people+1},(_,n)=>`<option value="${n}" ${state.veg===n?'selected':''}>${n===0?'None':n===state.people?`Everyone (${n})`:n}</option>`).join('')}</select><p class="planner-note">Vegetarian is a menu category, not a guarantee about allergens or shared preparation. Check dietary requirements directly with the restaurant.</p><div class="planner-actions"><button class="gold-button">Continue</button><button type="button" class="plain-button" data-back>Back</button></div></form>`}
 if(state.step===2){body.innerHTML=`<p class="step-meta">3 OF 3 · YOUR BUDGET</p><p class="chat-bubble">What’s your food budget for the whole table?</p><div class="choice-grid">${[100,150,200,300].map(n=>`<button data-budget="${n}">${money(n)}</button>`).join('')}<button data-budget="none">No limit</button></div><form id="budget-form"><label class="field-label" for="budget">Or enter your budget in AED</label><input class="planner-input" id="budget" type="number" min="1" max="10000" step="1" value="${state.budget||''}" required placeholder="e.g. 180"><div class="planner-actions"><button class="gold-button">Find my feast</button><button type="button" class="plain-button" data-back>Back</button></div></form><p class="planner-note">Estimates exclude delivery and other checkout charges. We plan one serves-one biryani per diner; appetite and final outlet portions may vary.</p>`}
 if(state.step===3){const plans=makePlans(state.people,state.veg,state.preferred);const allOver=state.budget&&plans.every(p=>total(p.items)>state.budget);body.innerHTML=`<p class="step-meta">${state.people} DINERS · ${state.veg} VEGETARIAN${state.budget?' · '+money(state.budget)+' BUDGET':''}</p><p class="chat-bubble">${allOver?'These complete-table options exceed your budget. Here are the estimates so you can adjust your plan.':'Two ways to make it a Behrouz evening.'}</p>${plans.map((p,i)=>`<article class="plan-card"><h3>${p.title}</h3><ul>${p.items.map(item=>`<li>${item.qty} × ${menu[item.id].name}</li>`).join('')}</ul><p class="plan-total"><span>Estimated food total</span><span>${money(total(p.items))}</span></p>${budgetNote(total(p.items))}<button class="gold-button" data-select-plan="${i}">Choose & customise</button></article>`).join('')}<button class="plain-button" data-back>Change budget</button><p class="planner-note">These are individual menu items grouped for your table, not official bundles or promotions.</p>`}
 if(state.step===4){const mains=state.items.filter(i=>i.id!=='dessert');body.innerHTML=`<p class="step-meta">YOUR FEAST · ${state.people} DINERS</p><p class="chat-bubble">Make it yours. Your estimate updates as you choose.</p>${mains.map((item,i)=>`<div class="edit-row"><span>${item.qty} ×</span><label><span class="field-label">${menu[item.id].veg?'Vegetarian biryani':'Non-vegetarian biryani'}</span><select data-edit="${i}" aria-label="Choose ${menu[item.id].veg?'vegetarian':'non-vegetarian'} biryani">${Object.entries(menu).filter(([id,m])=>id!=='dessert'&&m.veg===menu[item.id].veg).map(([id,m])=>`<option value="${id}" ${id===item.id?'selected':''}>${m.name} · AED ${m.price}</option>`).join('')}</select></label></div>`).join('')}<label class="check-row"><input id="dessert" type="checkbox" ${state.items.some(i=>i.id==='dessert')?'checked':''}>Add ${state.people} Gulab Jamun menu items · ${money(state.people*5)}</label><p class="plan-total"><span>Estimated food total</span><span id="final-total">${money(total(state.items))}</span></p><div id="budget-note">${budgetNote(total(state.items))}</div><p class="planner-note">No order has been placed. The official menu opens separately; your selections do not transfer automatically. Copy your plan to use as a reference, then choose your outlet and add the items there.</p><a class="gold-button official-cta" href="https://order.behrouzbiryani.com/menu" target="_blank" rel="noopener">Continue to official menu</a><div class="planner-actions"><button class="plain-button" id="copy-plan">Copy my feast</button><button class="plain-button" data-back>See both ideas</button></div><p id="copy-status" class="copy-status" role="status"></p><p class="planner-note">Confirm current prices, availability, portion sizes, ingredients and allergens with the restaurant before ordering.</p>`}
 body.scrollTop=0;
}
function refreshTotal(){$('#final-total').textContent=money(total(state.items));$('#budget-note').innerHTML=budgetNote(total(state.items));$('#copy-status').textContent=''}
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;
 if(b.hasAttribute('data-plan'))openPlan(Number(b.dataset.plan)||undefined);
 if(b.dataset.dish)openPlan(undefined,b.dataset.dish);
 if(b.dataset.close)$('#'+b.dataset.close).close();
 if(b.hasAttribute('data-back'))back();
 if(b.dataset.people){state.people=Number(b.dataset.people);state.veg=state.preferred==='veg'?state.people:Math.min(state.veg,state.people);next()}
 if(b.dataset.budget){state.budget=b.dataset.budget==='none'?null:Number(b.dataset.budget);next()}
 if(b.dataset.selectPlan!==undefined){state.items=makePlans(state.people,state.veg,state.preferred)[Number(b.dataset.selectPlan)].items;next()}
 if(b.id==='copy-plan'){const summary=`My Behrouz feast\n${state.items.map(i=>`${i.qty} × ${menu[i.id].name}`).join('\n')}\nEstimated food total: ${money(total(state.items))}\nFinal prices and availability on the official UAE menu. Delivery and checkout charges excluded.`;try{await navigator.clipboard.writeText(summary);$('#copy-status').textContent='Feast copied. Keep it handy on the official menu.'}catch{$('#copy-status').textContent='Copy is unavailable in this browser. Your plan is shown above; take a screenshot to keep it.'}}
 if(b.dataset.reveal){show(pack);const ticket=++viewerTicket;$('#modelStatus').hidden=false;$('#modelError').hidden=true;$('#modelStatus').textContent='Loading the interactive model…';try{const {mountPackaging}=await import('./packaging.js');if(pack.open&&ticket===viewerTicket)disposeViewer=mountPackaging({packDesign:b.dataset.reveal,packLayer:'all'})}catch{$('#modelStatus').textContent='The 3D viewer could not load. Close and reopen to try again.'}}
});
body.addEventListener('submit',e=>{e.preventDefault();if(e.target.id==='people-form'){state.people=Number($('#diners').value);state.veg=state.preferred==='veg'?state.people:Math.min(state.veg,state.people)}if(e.target.id==='veg-form')state.veg=Number($('#vegetarians').value);if(e.target.id==='budget-form')state.budget=Number($('#budget').value);next()});
body.addEventListener('change',e=>{if(e.target.dataset.edit!==undefined){state.items[Number(e.target.dataset.edit)].id=e.target.value;refreshTotal()}if(e.target.id==='dessert'){state.items=state.items.filter(i=>i.id!=='dessert');if(e.target.checked)state.items.push({id:'dessert',qty:state.people});refreshTotal()}});
pack.addEventListener('close',()=>{viewerTicket++;disposeViewer?.();disposeViewer=null});
for(const dialog of [planner,pack])dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});
